/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"


void
prog_100(char *host, int a, int b)
{
	CLIENT *clnt;
	int  *result_1;
	operandos  add_100_arg;
	add_100_arg.x = a;
	add_100_arg.y = b;

	int  *result_2;
	operandos  sub_100_arg;
	sub_100_arg.x = a;
	sub_100_arg.y = b;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		printf("ERRO");
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Chamando a função\n");
	result_1 = add_100(&add_100_arg, clnt);
	printf("Client - Resultado1 = %d\n", *result_1);
	if (result_1 == (int *) NULL) {
		printf("ERRO 2");
		clnt_perror (clnt, "call failed");
	}
	result_2 = sub_100(&sub_100_arg, clnt);
	printf("Client - Resultado2 = %d\n", *result_2);
	if (result_2 == (int *) NULL) {
		printf("ERRO 2");
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	int param_a = atoi(argv[2]);
	int param_b = atoi(argv[3]);
	prog_100 (host, param_a, param_b);
exit (0);
}
