/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"

int *
add_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x + argp->y;
	printf("Realizando: %d + %d = %d\n", argp->x, argp->y, result);

	return &result;
}

int *
sub_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x - argp->y;
	printf("Realizando: %d - %d = %d\n", argp->x, argp->y, result);

	return &result;
}
