/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "trab1.h"

float *
greater_001_svc(operandos *argp, struct svc_req *rqstp)
{
	static float result;

	if(argp->i == 0) {
		result = argp->num;
		return &result;
	}

	if (argp->num > argp->maior) {
		result = argp->num; 
	}

	if (argp->maior > argp->num) {
		result = argp->maior; 
	}

	return &result;
}

float *
less_001_svc(operandos *argp, struct svc_req *rqstp)
{
	static float  result;

	if(argp->i == 0) {
		result = argp->num;
		return &result;
	}

	if (argp->num < argp->menor) {
		result = argp->num; 
	}

	if (argp->menor < argp->num) {
		result = argp->menor; 
	}

	return &result;
}
