/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRAB1_H_RPCGEN
#define _TRAB1_H_RPCGEN
#define MAX 500000

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	float maior;
	float menor;
	float num;
	int i;
};
typedef struct operandos operandos;

#define PROG 55555550
#define VERSAO 001

#if defined(__STDC__) || defined(__cplusplus)
#define greater 1
extern  float * greater_001(operandos *, CLIENT *);
extern  float * greater_001_svc(operandos *, struct svc_req *);
#define less 3
extern  float * less_001(operandos *, CLIENT *);
extern  float * less_001_svc(operandos *, struct svc_req *);
extern int prog_001_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define greater 1
extern  float * greater_001();
extern  float * greater_001_svc();
#define less 3
extern  float * less_001();
extern  float * less_001_svc();
extern int prog_001_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);

#else /* K&R C */
extern bool_t xdr_operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRAB1_H_RPCGEN */
