/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "trab1.h"
#include <math.h>
#define MAX 500000


void
prog_001(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	operandos  greater_001_arg;
	float  *result_2;
	operandos  less_001_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	float vetor[MAX];

	for(int i=0; i<MAX; i++) {
		vetor[i] = sqrt(rand() % MAX + 1);
		printf("[Client] vetor[%d] = %.2f\n", i, vetor[i]);
	}


	greater_001_arg.maior = 0;

	for(int i=0; i<MAX; i++) {
		greater_001_arg.i = i;
		greater_001_arg.num = vetor[i];

		result_1 = greater_001(&greater_001_arg, clnt);
		
		if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
		}
		
		greater_001_arg.maior = *result_1;

	}
	
	
	less_001_arg.menor = 0;

	for(int i=0; i<MAX; i++) {
		less_001_arg.i = i;
		less_001_arg.num = vetor[i];

		result_2 = less_001(&less_001_arg, clnt);

		if (result_2 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		less_001_arg.menor = *result_2;
	}

	printf("[Server] MAIOR: %.2f e MENOR:%.2f\n", greater_001_arg.maior, less_001_arg.menor);

	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	prog_001 (host);
exit (0);
}
