/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "trab1.h"

bool_t
xdr_operandos (XDR *xdrs, operandos *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->maior))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->menor))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->i))
		 return FALSE;
	return TRUE;
}
