# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lab2_pb2 as lab2__pb2


class Lab2Stub(object):
    """Retorna menor e maior valores de um array de 500 mil floats
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LessGreaterNumber = channel.unary_unary(
                '/lab2.Lab2/LessGreaterNumber',
                request_serializer=lab2__pb2.Array.SerializeToString,
                response_deserializer=lab2__pb2.Response.FromString,
                )


class Lab2Servicer(object):
    """Retorna menor e maior valores de um array de 500 mil floats
    """

    def LessGreaterNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Lab2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LessGreaterNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.LessGreaterNumber,
                    request_deserializer=lab2__pb2.Array.FromString,
                    response_serializer=lab2__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lab2.Lab2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Lab2(object):
    """Retorna menor e maior valores de um array de 500 mil floats
    """

    @staticmethod
    def LessGreaterNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lab2.Lab2/LessGreaterNumber',
            lab2__pb2.Array.SerializeToString,
            lab2__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
